# Generated by Django 4.2 on 2024-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0002_alter_category_name_alter_post_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
