# Generated by Django 4.2.7 on 2024-02-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0003_alter_post_options_alter_post_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
