# Generated by Django 4.2.7 on 2024-02-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_added']},
        ),
    ]
